### ISSUE TITLE
Epic 1:  Implement "Activities" Feature

### ISSUE THREAD

**Issue by Sharu201101** [BitBytes-team/Project-8#1]
Issue definition : As a developer, I need the assignee to implement the "Activities" feature to provide users with a view of the 5 most recent activities on the site. This includes displaying activities in reverse chronological order, presenting relevant details such as date, time, user name, and specific information based on the activity type (e.g., thumbnails for photos, comment authors for comments). The feature should seamlessly integrate with the database to store activity records and efficiently compute the activity history.

Acceptance Criteria:
Navigation:
The "Activities" button in the toolbar should smoothly transition users to a dedicated activity view.
Activity Display:
The activity view must prominently display the 5 most recent activities.
Activities should be sorted in reverse chronological order, with the most recent at the top.
Activity Information:
Each activity entry should clearly present the date and time of occurrence.
The name of the user who performed the activity should be visible.
The type of activity (Photo Upload, New Comment, etc.) should be clearly indicated.
Photo Upload Activity:
For photo upload activities, a small thumbnail of the uploaded photo should be visible.
Comment Added Activity:
For comment added activities, a small thumbnail of the associated photo should be visible.
The name of the comment author should be displayed.
User Registration Activity:
User registration activities should not include additional information beyond the user's name and registration timestamp.
User Login Activity:
User login activities should not include additional information.
User Logout Activity:
User logout activities should not include additional information.
Real-time Updates or Manual Refresh:
The activity view should update itself automatically when new activities occur.
Alternatively, a manual refresh button should be available for users to trigger an update.
Database Integration:
Extend the database schema to store records of activities, mapping well to MongoDB.
Ensure the query mechanism computes the activity history across activity record objects efficiently.
Pre-existing Entries:
Do not display entries in the activity feed for pre-existing comments and photos in the seeded database.

**Comment by Jahnavi-0305** [comment]
The activityFeed.jsx component has been created and the following activities are shown in the activity board: 
- A photo upload - show a small thumbnail of the photo
- A comment added - show a small thumbnail of the photo and the comment author's name
- User registering - no additional info
- User logging in - no additional info
- User logging out - no additional info
Changes has been made in userPhotos.jsx, topBar.jsx, Loginregister.jsx , PhotoShare.jsx and webserver.js to display the activities above in the activity board. 

activityFeed.jsx: 

import React from 'react';
import axios from "axios";
import {
    Typography, Button
    } from '@mui/material';
class Activity extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            activityList: [],
        };
    }

    componentDidMount() {
        axios.get('/activity')
        .then((res) => {
                this.setState({activityList: res.data});  
                console.log(res.data);
                //console.log(this.props.User);
            })
        .catch((err) => {
                console.log(err);
            });
    }

    handleRefersh = ()=>{
        axios.get('/activity')
        .then((res) => {
                this.setState({activityList: res.data});
            })
        .catch((err) => {
                console.log(err);
            });
    };

    render() {
        const { user } = this.props;
        let innerHTML = [];

        for (let i = 0; i < this.state.activityList.length; i++) {
            let cur = this.state.activityList[i];
            console.log('Uploaded Photo File Name:', cur.uploaded_photo_file_name);
            console.log(cur);
            innerHTML.push(
                <Typography variant="body2" key = {i}>
                    <br/>
                    {new Date(cur.date_time).toLocaleString()}
                    <br/>
                    {user.first_name + " " + cur.type + " "}
                    {cur.commented_photo_author !== null && `${cur.commented_photo_author}'s photo`}
                    {cur.uploaded_photo_file_name !== null && <> <br/> <img src ={`/images/${cur.uploaded_photo_file_name}`} width={120} height={120} /> </> }
                    {cur.commented_photo_file_name !== null && <> <br/> <img src ={"/images/" + cur.commented_photo_file_name} width = {120} height ={120} /> </>}
                    <br/>
                </Typography>
            );
        }
        
        return (
            <div style={{maxHeight: '100%', overflow: 'auto'}}>
                <Typography variant="h5">Activity Board</Typography>
                {innerHTML}
                <br/>
                <Button variant="outlined" onClick={this.handleRefersh}> Refresh </Button>
            </div>
        );
    }

}

export default Activity;

Extra activities like deleting comments, photos and liking photos need to added yet.

**Comment by Jahnavi-0305** [comment]
Changes has been made in userPhotos.jsx, userDetail.jsx and webserver.js to display the activities below in the activity board.

- A photo delete - show a small thumbnail of the photo that is deleted with author's name
- A comment deleted- show a small thumbnail of the photo and the comment author's name
- A user delete - no additional info
- A user like and unliking photo - show a small thumbnail of the photo which has be liked or unliked and author's name

the updated code: 
activityFeed.jsx:

import React from 'react';
import axios from "axios";
import {
    Typography, Button
    } from '@mui/material';
class Activity extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            activityList: [],
        };
    }

    componentDidMount() {
        axios.get('/activity')
        .then((res) => {
                this.setState({activityList: res.data});  
                console.log(res.data);
                //console.log(this.props.User);
            })
        .catch((err) => {
                console.log(err);
            });
    }

    handleRefersh = ()=>{
        axios.get('/activity')
        .then((res) => {
                this.setState({activityList: res.data});
            })
        .catch((err) => {
                console.log(err);
            });
    };

    render() {
        const { user } = this.props;
        let innerHTML = [];

        for (let i = 0; i < this.state.activityList.length; i++) {
            let cur = this.state.activityList[i];
            //console.log('Uploaded Photo File Name:', cur.uploaded_photo_file_name);
            //console.log(cur);
            innerHTML.push(
                <Typography variant="body2" key = {i}>
                    <br/>
                    {new Date(cur.date_time).toLocaleString()}
                    <br/>
                    {user.first_name + " " + cur.type + " "}
                    {cur.commented_photo_author !== null && `${cur.commented_photo_author}'s photo`}
                    {cur.uploaded_photo_file_name !== null && <> <br/> <img src ={`/images/${cur.uploaded_photo_file_name}`} width={120} height={120} /> </> }
                    {cur.commented_photo_file_name !== null && <> <br/> <img src ={"/images/" + cur.commented_photo_file_name} width = {120} height ={120} /> </>}
                    {cur.deleted_photo_file_name !== null && <> <br/> <img src ={"/images/" + cur.deleted_photo_file_name} width = {120} height ={120} /> </>}
                    {cur.deleted_comment_file_name !== null && <> <br/> <img src ={"/images/" + cur.deleted_comment_file_name} width = {120} height ={120} /> </>}
                    {cur.liked_photo_file_name !== null && <> <br/> <img src ={"/images/" + cur.liked_photo_file_name} width = {120} height ={120} /> </>}
                    {cur.Unliked_photo_file_name !== null && <> <br/> <img src ={"/images/" + cur.Unliked_photo_file_name} width = {120} height ={120} /> </>}
                    <br/>
                </Typography>
            );
        }
        
        return (
            <div style={{maxHeight: '100%', overflow: 'auto'}}>
                <Typography variant="h5">Activity Board</Typography>
                {innerHTML}
                <br/>
                <Button variant="outlined" onClick={this.handleRefersh}> Refresh </Button>
            </div>
        );
    }

}

export default Activity;
